baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Docdock test"
theme = "docdock-multilanguage"

[params]
editURL = "https://github.com/jose-oc/test-hugo-theme-docdock/edit/master/"
showVisitedLinks = true # default is false
themeStyle = "theme" # overide base css
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "title" # ordersectionsby = "weight"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
# When using mulitlingual website, disable the switch language button.
disableLanguageSwitchingButton = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/jose-oc/hugo-theme-docdock"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30


[Languages]
[Languages.en]
title = "Docdock test - En"
weight = 1
languageName = "English"

[Languages.es]
title = "Docdock test - Es"
weight = 10
languageName = "Español"


[[Languages.es.menu.shortcuts]]
pre = "<h3>Más</h3>"
name = "<i class='fa fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/jose-oc/hugo-theme-docdock"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Documentación sobre Hugo"
identifier = "hugodocs"
url = "https://gohugo.io/"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Créditos"
url = "/credits"
weight = 30